# Generated by Django 3.1.5 on 2021-07-02 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, verbose_name='Caption')),
                ('status', models.PositiveSmallIntegerField(choices=[
                 (1, 'pending'), (2, 'approved'), (3, 'disapproved')], default=1)),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('asset', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='asset.asset', verbose_name='Image')),
                ('likes', models.ManyToManyField(
                    related_name='post_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                           related_name='post_owner', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Comment text')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
