# Generated by Django 3.1.5 on 2021-07-04 19:59

import asset.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file_low',
            field=models.FileField(blank=True, null=True, upload_to=asset.models.upload_directory_path),
        ),
        migrations.AddField(
            model_name='asset',
            name='file_medium',
            field=models.FileField(blank=True, null=True, upload_to=asset.models.upload_directory_path),
        ),
    ]
